# Generated by Django 5.1.1 on 2026-04-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("mother_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("semester", models.IntegerField()),
                ("roll", models.IntegerField(unique=True)),
                ("reg", models.IntegerField(unique=True)),
                ("session", models.CharField(max_length=20)),
                (
                    "shift",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Day", "Day")], max_length=10
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=5, null=True)),
                ("mobile_number", models.CharField(max_length=15)),
                (
                    "alternate_mobile",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("present_address", models.TextField()),
                ("permanent_address", models.TextField()),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_number", models.CharField(max_length=15)),
                ("nationality", models.CharField(default="Bangladeshi", max_length=50)),
                ("religion", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
