# Generated by Django 5.2.16 on 2026-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='env_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_token', models.CharField(max_length=255)),
                ('moceanapi_token', models.CharField(max_length=255)),
            ],
        ),
    ]
