# Generated by Django 5.2.16 on 2026-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_loginhistory_asn_loginhistory_calling_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='ipinfo_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
